export const CLEAR_CROSSWORD = 'CLEAR_CROSSWORD';
export const SET_INITIAL_CROSSWORD = 'SET_INITIAL_CROSSWORD';
export const SET_PICTURE_CROSSWORD = 'SET_PICTURE_CROSSWORD';
export const SET_HEADERS_CROSSWORD = 'SET_PICTURE_CROSSWORD';
export const SET_CHANGE_ITEM_CROSSWORD = 'SET_CHANGE_ITEM_CROSSWORD';
export const SET_IS_SHOW = 'SET_IS_SHOW';

export const SET_CATHEDRA_NAME = 'SET_CATHEDRA_NAME';
export const SET_CATHEDRA_ZAV_NAME = 'SET_CATHEDRA_ZAV_NAME';
export const SET_CATHEDRA_TEL = 'SET_CATHEDRA_TEL';
export const SET_EMPLOYEE_NAME = 'SET_EMPLOYEE_NAME';
export const SET_EMPLOYEE_POSITION = 'SET_EMPLOYEE_POSITION';
export const SET_EMPLOYEE_ADDRESS = 'SET_EMPLOYEE_ADDRESS';
export const SET_EMPLOYEE_TEL = 'SET_EMPLOYEE_TEL';
export const SET_SALARY_TOTAL = 'SET_SALARY_TOTAL';
export const SET_SALARY_PAY = 'SET_SALARY_PAY';
export const SET_SALARY_KEEP = 'SET_SALARY_KEEP';
export const SET_SALARY_PREMIUM = 'SET_SALARY_PREMIUM';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const RESET_FORM = 'RESET_FORM';

export const SET_WORKER_NAME = 'SET_WORKER_NAME';
export const SET_WORKER_DATE = 'SET_WORKER_DATE';
export const ADD_WORKER = 'ADD_WORKER';
