export const CLEAR_CROSSWORD = 'CLEAR_CROSSWORD';
export const SET_INITIAL_CROSSWORD = 'SET_INITIAL_CROSSWORD';
export const SET_PICTURE_CROSSWORD = 'SET_PICTURE_CROSSWORD';
export const SET_HEADERS_CROSSWORD = 'SET_PICTURE_CROSSWORD';
export const SET_CHANGE_ITEM_CROSSWORD = 'SET_CHANGE_ITEM_CROSSWORD';
export const SET_IS_SHOW = 'SET_IS_SHOW';
